title: Kristine Zheng
url: "https://kristinezheng.github.io/"
baseurl: "/"

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://kristinezheng.github.io/"
footer_text: "Adapted from Design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "cv"
#  - name: "Contact"
#    link: "contact"
 - name: "Misc"
   link: "miscellaneous"
